"""Add user field in battle

Revision ID: 0c7e921d6bb8
Revises: dfca0afa746e
Create Date: 2026-08-31 23:42:31.391922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7e921d6bb8'
down_revision: Union[str, Sequence[str], None] = 'dfca0afa746e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'battles', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'battles', type_='foreignkey')
    op.drop_column('battles', 'user')
    # ### end Alembic commands ###
