"""changing types hero

Revision ID: 209de859419d
Revises: dd663924742f
Create Date: 2026-08-26 09:01:53.277834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209de859419d'
down_revision: Union[str, Sequence[str], None] = 'dd663924742f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('heroes', 'real_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('heroes', 'deck',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    op.alter_column('heroes', 'gender',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('heroes', 'origin',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('heroes', 'apperance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('heroes', 'first_appearance_comic',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('heroes', 'image_hero',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('heroes', 'image_hero',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('heroes', 'first_appearance_comic',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('heroes', 'apperance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('heroes', 'origin',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('heroes', 'gender',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('heroes', 'deck',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    op.alter_column('heroes', 'real_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
