"""Initial Migration

Revision ID: 31caa76d21d7
Revises: 
Create Date: 2026-08-22 13:48:55.613256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31caa76d21d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_heroes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('special_attack_effect', sa.Integer(), nullable=False),
    sa.Column('special_attack_name', sa.String(length=50), nullable=False),
    sa.Column('required_energy', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('special_attack_effect'),
    sa.UniqueConstraint('special_attack_name')
    )
    op.create_index(op.f('ix_class_heroes_id'), 'class_heroes', ['id'], unique=True)
    op.create_table('hyper_attacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('effect', sa.Integer(), nullable=False),
    sa.Column('required_energy', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_hyper_attacks_id'), 'hyper_attacks', ['id'], unique=True)
    op.create_table('packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('deck', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_packs_id'), 'packs', ['id'], unique=True)
    op.create_table('places',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=1000), nullable=False),
    sa.Column('effect', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=True)
    op.create_table('run_hero_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('drawback', sa.Integer(), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_hero_states_id'), 'run_hero_states', ['id'], unique=True)
    op.create_table('active_tower_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_tower', sa.Integer(), nullable=False),
    sa.Column('current_floor', sa.Integer(), nullable=False),
    sa.Column('active_buff', sa.Integer(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_tower_runs_id'), 'active_tower_runs', ['id'], unique=True)
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('real_name', sa.String(length=100), nullable=False),
    sa.Column('deck', sa.String(length=5000), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Integer(), nullable=False),
    sa.Column('birth', sa.DateTime(), nullable=True),
    sa.Column('apperance', sa.Integer(), nullable=False),
    sa.Column('first_appearance_date', sa.DateTime(), nullable=False),
    sa.Column('first_appearance_comic', sa.String(length=1000), nullable=False),
    sa.Column('image_hero', sa.String(length=1000), nullable=False),
    sa.Column('nemesis', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('class', sa.Integer(), nullable=False),
    sa.Column('hyper_attack', sa.Integer(), nullable=False),
    sa.Column('base_atk', sa.Integer(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_def', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class'], ['class_heroes.id'], ),
    sa.ForeignKeyConstraint(['hyper_attack'], ['hyper_attacks.id'], ),
    sa.ForeignKeyConstraint(['nemesis'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck'),
    sa.UniqueConstraint('image_hero'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_heroes_id'), 'heroes', ['id'], unique=True)
    op.create_table('hero_packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('pack', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['pack'], ['packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_packs_id'), 'hero_packs', ['id'], unique=True)
    op.create_table('user_heroes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hero', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('fragments', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hero'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_heroes_id'), 'user_heroes', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('highest_level', sa.Integer(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_level'], ['active_tower_runs.id'], ),
    sa.ForeignKeyConstraint(['highest_level'], ['active_tower_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('decks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_id'), 'decks', ['id'], unique=True)
    op.create_table('battles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('floor_reached', sa.Integer(), nullable=False),
    sa.Column('deck', sa.Integer(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['floor_reached'], ['active_tower_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battles_id'), 'battles', ['id'], unique=True)
    op.create_table('deck_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_hero', sa.Integer(), nullable=False),
    sa.Column('deck', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['user_hero'], ['user_heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_slots_id'), 'deck_slots', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deck_slots_id'), table_name='deck_slots')
    op.drop_table('deck_slots')
    op.drop_index(op.f('ix_battles_id'), table_name='battles')
    op.drop_table('battles')
    op.drop_index(op.f('ix_decks_id'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_heroes_id'), table_name='user_heroes')
    op.drop_table('user_heroes')
    op.drop_index(op.f('ix_hero_packs_id'), table_name='hero_packs')
    op.drop_table('hero_packs')
    op.drop_index(op.f('ix_heroes_id'), table_name='heroes')
    op.drop_table('heroes')
    op.drop_index(op.f('ix_active_tower_runs_id'), table_name='active_tower_runs')
    op.drop_table('active_tower_runs')
    op.drop_index(op.f('ix_run_hero_states_id'), table_name='run_hero_states')
    op.drop_table('run_hero_states')
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_packs_id'), table_name='packs')
    op.drop_table('packs')
    op.drop_index(op.f('ix_hyper_attacks_id'), table_name='hyper_attacks')
    op.drop_table('hyper_attacks')
    op.drop_index(op.f('ix_class_heroes_id'), table_name='class_heroes')
    op.drop_table('class_heroes')
    # ### end Alembic commands ###
