"""Merge tables UserHero and RunHeroState

Revision ID: 55a0e54200b7
Revises: eac58b8844cd
Create Date: 2026-08-31 13:49:55.930811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a0e54200b7'
down_revision: Union[str, Sequence[str], None] = 'eac58b8844cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_heroes', sa.Column('current_hp', sa.Integer(), nullable=False))
    op.add_column('user_heroes', sa.Column('drawback', sa.Integer(), nullable=False))
    op.add_column('user_heroes', sa.Column('alive', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_heroes', 'alive')
    op.drop_column('user_heroes', 'drawback')
    op.drop_column('user_heroes', 'current_hp')
    # ### end Alembic commands ###
