"""Add user id on user_hero

Revision ID: 7c139bce6673
Revises: fa4ebbadab59
Create Date: 2026-08-31 09:10:35.886380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c139bce6673'
down_revision: Union[str, Sequence[str], None] = 'fa4ebbadab59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_heroes', sa.Column('user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_heroes', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_heroes', type_='foreignkey')
    op.drop_column('user_heroes', 'user')
    # ### end Alembic commands ###
