"""Add active field

Revision ID: ae19bfe4af66
Revises: 209de859419d
Create Date: 2026-08-26 10:23:11.496822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae19bfe4af66'
down_revision: Union[str, Sequence[str], None] = '209de859419d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_tower_runs', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('class_heroes', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('deck_slots', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('decks', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('hero_packs', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('hyper_attacks', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('packs', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('places', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('run_hero_states', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('user_heroes', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_heroes', 'active')
    op.drop_column('run_hero_states', 'active')
    op.drop_column('places', 'active')
    op.drop_column('packs', 'active')
    op.drop_column('hyper_attacks', 'active')
    op.drop_column('hero_packs', 'active')
    op.drop_column('decks', 'active')
    op.drop_column('deck_slots', 'active')
    op.drop_column('class_heroes', 'active')
    op.drop_column('active_tower_runs', 'active')
    # ### end Alembic commands ###
