"""Merge tables UserHero and RunHeroState V2

Revision ID: bbd69f9bdda3
Revises: 55a0e54200b7
Create Date: 2026-08-31 14:32:28.494151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd69f9bdda3'
down_revision: Union[str, Sequence[str], None] = '55a0e54200b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_hero_states_id'), table_name='run_hero_states')
    op.drop_table('run_hero_states')
    op.add_column('user_heroes', sa.Column('max_hp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_heroes', 'max_hp')
    op.create_table('run_hero_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('current_hp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drawback', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_hero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_hero'], ['user_heroes.id'], name=op.f('run_hero_states_user_hero_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('run_hero_states_pkey'))
    )
    op.create_index(op.f('ix_run_hero_states_id'), 'run_hero_states', ['id'], unique=True)
    # ### end Alembic commands ###
