"""adjustings

Revision ID: c598386566d8
Revises: eed18397a442
Create Date: 2026-08-27 12:34:19.822593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c598386566d8'
down_revision: Union[str, Sequence[str], None] = 'eed18397a442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('class_heroes_special_attack_effect_key'), 'class_heroes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('class_heroes_special_attack_effect_key'), 'class_heroes', ['special_attack_effect'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
