"""changing types

Revision ID: dd663924742f
Revises: 31caa76d21d7
Create Date: 2026-08-25 07:53:44.763825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd663924742f'
down_revision: Union[str, Sequence[str], None] = '31caa76d21d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('heroes', 'birth',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('heroes', 'first_appearance_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('first_appearance_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('heroes', 'birth',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
