"""Merge tables UserHero and RunHeroState V3

Revision ID: dfca0afa746e
Revises: bbd69f9bdda3
Create Date: 2026-08-31 14:38:38.654414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfca0afa746e'
down_revision: Union[str, Sequence[str], None] = 'bbd69f9bdda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_heroes', 'drawback',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_heroes', 'drawback',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
