"""Add user_hero in run_state_hero

Revision ID: eac58b8844cd
Revises: 7c139bce6673
Create Date: 2026-08-31 12:25:07.525897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac58b8844cd'
down_revision: Union[str, Sequence[str], None] = '7c139bce6673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_hero_states', sa.Column('user_hero', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'run_hero_states', 'user_heroes', ['user_hero'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run_hero_states', type_='foreignkey')
    op.drop_column('run_hero_states', 'user_hero')
    # ### end Alembic commands ###
