"""Add price in pack

Revision ID: fa4ebbadab59
Revises: c598386566d8
Create Date: 2026-08-28 12:50:51.413144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4ebbadab59'
down_revision: Union[str, Sequence[str], None] = 'c598386566d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packs', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packs', 'price')
    # ### end Alembic commands ###
